---
proxmox_snapshot_retention: 3
apt_archive_path: /var/cache/apt/archives
apt_cache_valid_time: 3600
apt_lock_timeout: 600
apt_min_archive_free_mb: 512
apt_retries: 10
apt_retry_delay: 30
apt_task_timeout: 3600
reboot_timeout: 1800
